uvmf:
  environments:
    controller:
      agents:
      - initiator_responder: RESPONDER
        name: controller_in_agent_inst
        type: controller_in
      - initiator_responder: RESPONDER
        name: controller_out_agent_inst
        type: controller_out
      analysis_components:
      - name: controller_predictor_inst
        parameters: []
        type: controller_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: controller_scoreboard_inst
        sb_type: uvmf_in_order_scoreboard
        trans_type: controller_out_transaction
      subenvs: []
      tlm_connections:
      - driver: controller_in_agent_inst.monitored_ap
        receiver: controller_predictor_inst.predictor_ae
        validate: 'True'
      - driver: controller_out_agent_inst.monitored_ap
        receiver: controller_scoreboard_inst.actual_analysis_export
        validate: 'True'
      - driver: controller_predictor_inst.predictor_ap
        receiver: controller_scoreboard_inst.expected_analysis_export
        validate: 'True'
